name: 'pmpm'
version: '0.0.2'
config-version: 2

profile: 'default'

vars:
    eligibility: |
        {% if var('pmpm_eligibility_override',none) is not none %}{{var('pmpm_eligibility_override')}}
        {%- elif var('eligibility_override',none) is not none %}{{var('eligibility_override')}}
        {%- else %}{{ref('eligibility')}}
        {%- endif %}

    pharmacy_claim: |
        {% if var('pmpm_pharmacy_claim_override',none) is not none %}{{var('pmpm_pharmacy_claim_override')}}
        {%- elif var('pharmacy_claim_override',none) is not none %}{{var('pharmacy_claim_override')}}
        {%- else %}{{ref('pharmacy_claim')}}
        {%- endif %}

    medical_claim: |
        {% if var('pmpm_medical_claim_override',none) is not none %}{{var('pmpm_medical_claim_override')}}
        {%- elif var('medical_claim_override',none) is not none %}{{var('medical_claim_override')}}
        {%- else %}{{ref('medical_claim')}}
        {%- endif %}

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
